name: C++ CI with GTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev googletest
        
    - name: Build GTest (if needed)
      run: |
        # Only build if libraries aren't already installed
        if [ ! -f /usr/lib/libgtest.a ] || [ ! -f /usr/lib/libgtest_main.a ]; then
          cd /usr/src/googletest
          sudo cmake CMakeLists.txt
          sudo make
          sudo mkdir -p /usr/lib
          sudo cp lib/*.a /usr/lib/
        fi
        
        
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure CMake
      working-directory: ./build
      run: cmake ..
      
    - name: Build project
      working-directory: ./build
      run: cmake --build .
      
    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure